# docker-compose.yml

version: '3.8'

services:
  
  backend:
    image: medwar-backend
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        PORT: 5000
    ports:
      - 5000:5000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  frontend:
    image: medwar-frontend
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    environment: 
      - API_URL=${API_URL}
      - GOOGLEMAPS_API_KEY=${GOOGLEMAPS_API_KEY}
    ports:
      - 8080:8080
    depends_on: 
      - backend

  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./resources:/resources
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data:
