# docker-compose.yml

version: '3.8'

services:
  
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    environment:
      - DB_URL=postgresql://${DB_USER}:${DB_PASS}@db:${DB_PORT}
      - DB_NAME=${DB_NAME}
      - GOOGLEMAPS_API_KEY=${GOOGLEMAPS_API_KEY}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}


  traefik:
    container_name: traefik
    build:
      context: .
      dockerfile: Dockerfile.traefik
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

volumes:
  postgres_data:
