# docker-compose.yml

version: '3.3'

services:
  
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}
      - DB_NAME=${DB_NAME}
      - GOOGLEMAPS_API_KEY=${GOOGLEMAPS_API_KEY}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data: