  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: medicine-warriors
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: medicine-warriors-pods
    template:
      metadata:
        labels:
          app: medicine-warriors-pods
      spec:
        securityContext:
          runAsNonRoot: true
        containers:
        - name: medicine-warriors-frontend
          image: medicinewarriors/medicine-warriors-frontend:5eeb444f333a89531ec998018ac1c1a8c7e374d2
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
          resources:
            requests:
              memory: "100Mi"
              cpu: "30m"
            limits:
              memory: "300Mi"
              cpu: "100m"
        - name: medicine-warriors-backend
          image: medicinewarriors/medicine-warriors-backend:5eeb444f333a89531ec998018ac1c1a8c7e374d2
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 5000
          resources:
            requests:
              memory: "100Mi"
              cpu: "30m"
            limits:
              memory: "300Mi"
              cpu: "100m"
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_HOST
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_URL
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_NAME
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_PORT
