  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: medicine-warriors-backend
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: medicine-warriors-backend-pods
    template:
      metadata:
        labels:
          app: medicine-warriors-backend-pods
      spec:
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        automountServiceAccountToken: false
        containers:
        - name: ctr-backend
          image: medicinewarriors/medicine-warriors-backend:5eeb444f333a89531ec998018ac1c1a8c7e374d2
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 5000
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            procMount: "Default"
          resources:
            requests:
              memory: "100Mi"
              cpu: "30m"
            limits:
              memory: "300Mi"
              cpu: "100m"
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_HOST
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_URL
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_NAME
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_PORT
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: medicine-warriors-frontend
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: medicine-warriors-frontend-pods
    template:
      metadata:
        labels:
          app: medicine-warriors-frontend-pods
      spec:
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containers:
        - name: ctr-frontend
          image: medicinewarriors/medicine-warriors-frontend:5eeb444f333a89531ec998018ac1c1a8c7e374d2
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            procMount: "Default"
          resources:
            requests:
              memory: "100Mi"
              cpu: "30m"
            limits:
              memory: "300Mi"
              cpu: "100m"
          env:
          - name: API_URL
            value: "http://medicine-warriors-backend.default.svc.cluster.local"
          - name: GOOGLEMAPS_API_KEY
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: GOOGLEMAPS_API_KEY