  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: medicine-warriors
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: medicine-warriors-pods
    template:
      metadata:
        labels:
          app: medicine-warriors-pods
      spec:
        securityContext:
          runAsNonRoot: true
        containers:
        - name: medicine-warriors-ctr
          image: medicinewarriors/medicine-warriors:9ddd4f74672eb53d2999644eb05cb77a139b14c6
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
          resources:
            requests:
              memory: "100Mi"
              cpu: "30m"
            limits:
              memory: "300Mi"
              cpu: "100m"
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_HOST
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_URL
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_NAME
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: DB_PORT
          - name: GOOGLEMAPS_API_KEY
            valueFrom:
              secretKeyRef:
                name: medicine-secrets
                key: GOOGLEMAPS_API_KEY
