apiVersion: v1
kind: Secret
metadata:
  name: medicine-secrets
  labels:
    app: medicine-warriors
type: Opaque
data:
  DB_URL: value
  DB_NAME: value
  GOOGLEMAPS_API_KEY: value
  DB_PORT: value

